type User {
    id: ID
    name: String
    email: String
    role : String
    password:String
}

type Product {
    id: ID
    name: String
    price: Float
    stock: Int
}

type Order {
    id: ID
    totalAmount: Float
    user: User
    orderItems : [OrderItem]
}

type OrderItem{
   id: ID
   quantity : Int
   price : Float
   product : Product

}

type Query {
    getAllProducts: [Product]
    getProductById(id: ID!): Product
    getAllUsers: [User]
    getAllOrders: [Order]
    getAllUserCached:[User]
}

type Mutation {
     registerUser(name: String!, email: String!, password: String!): User
        loginUser(name: String!, email: String!, password: String!): String
        createProduct(name: String!, price: Float!, stock: Int!): Product
        createOrder(productId: ID!, quantity: Int!): Order
}

